### ISSUE TITLE
mangafox Not showing Complete Chapter List

### ISSUE THREAD

**Issue by subhang** [jiaweihli/manga_downloader#53]
MangaFox is not showing complete chapters list

**Comment by keikatsuga** [comment]
I also encounter this error on 'Berserk' manga.

The program did not show the chapter that is not grouped in Volume. In this case, only chapter from volume 37 and 38 is available (ch 325 - ch 337). 
Chapter 1-324 is grouped in 'Volume not available' on mangafox site, but doesn't show up at all on the program.

**Comment by aurevec** [comment]
Yes, I have the same problem with Berserk.

**Comment by CharlieCorner** [comment]
This was resolved on issue #89 It's been a while since anybody commented on here, so @jiaweihli , it's up to you to decide if you want to keep this issue open or if you want to close it too.

**Comment by jiaweihli** [comment]
Done, please re-open if you're still seeing issues.
