### ISSUE TITLE
Downloader and compressor broken?

### ISSUE THREAD

**Issue by hex007** [jiaweihli/manga_downloader#62]
I have tried all the regex in the mangapanda parser and they all work and yet none of the pages get downloaded with this error

Some images were not downloaded due to unavailability on the site or temporary ip banning:

I can easily browse from browser so ip banning may not be an issue.

**Comment by jiaweihli** [comment]
Interesting...I wonder if they have different anti-scraping heuristics aside from user-agent.  Feel free to submit a PR if you find some!

**Comment by hex007** [comment]
So i know there is a verbose option to the program but can the processing be restricted to one thread. The command line help doesn't specify if the number of threads used can be changed.

**Comment by jiaweihli** [comment]
There's a `-t` option for threads, it defaults to 3.

**Comment by hex007** [comment]
So i think i have found the place where the problem occurs. and have corrected it. now how do i do the pull request.

**Comment by jiaweihli** [comment]
Take a look at https://help.github.com/articles/using-pull-requests/

**Comment by hex007** [comment]
Finally got it right
