### ISSUE TITLE
Please provide more help examples!

### ISSUE THREAD

**Issue by reek12** [jiaweihli/manga_downloader#77]
Could you please provide more help examples? Like the last version? The -h tag isnt very helpful.. Could you add more verbose help?.. Thanks...

**Comment by jiaweihli** [comment]
Is [this](https://github.com/jiaweihli/manga_downloader#usage-1) what you're looking for?

**Comment by reek12** [comment]
No. I was looking for the 1.0.0 branch that uses mangopi library... I couldn't use the commands of earlier version either. It's just giving invalid choice error. Sorry for late reply

**Comment by jiaweihli** [comment]
Ah, yeah the mangopi version is an entirely new codebase.  Unfortunately I haven't had much time to work on it lately, so it's still missing a lot of documentation.
