### ISSUE TITLE
Adding a build-a-Tankoubon (volume) functionality

### ISSUE THREAD

**Issue by CharlieCorner** [jiaweihli/manga_downloader#84]
Imagine that you are behind in reading Bleach, or Naruto, or DragonBall and you need to catch up. We're talking about being >150 chapters behind.

You could set manga_downloader to download all of these chapters; and you could read them one by one. Once you're done with one chapter you'd have to search for the next one, open it up and read it. Rinse and repeat.

Now imagine you like to read these on your ebook reader. It becomes too much of a hassle.

What if we could group our chapters in a neatly ordered [tankoubon](https://en.wikipedia.org/wiki/Tank%C5%8Dbon)? Like the ones you can get at any book store. You could then have a volume with 'n' number of chapters in it. It'd be easier to read in your favorite comic reader.

You should be able to control how many chapters you want in a given volume and have the option to optionally remove the individual chapter files once you are done compiling them into it.

**Comment by CharlieCorner** [comment]
I've been working on this feature request in my spare time and will submit a Pull Request for review.

**Comment by jiaweihli** [comment]
Done in #85
