### ISSUE TITLE
Listing chapters from Mangafox will sometimes not retrieve the complete list

### ISSUE THREAD

**Issue by CharlieCorner** [jiaweihli/manga_downloader#89]
When listing chapters for Onepunch-man, Bleach or Naruto, the list printed by manga_downloader is not complete.

For instance, for [Onepunch-man](http://mangafox.me/manga/onepunch_man/) manga_downloader will list a little over 30 chapters, when in reality, Mangafox lists over 60 on its website.

**Comment by jiaweihli** [comment]
Most likely culprit here is a parsing issue with the chapter regex - does your [commit in #88](https://github.com/jiaweihli/manga_downloader/pull/88/commits/76f7ad44503f8cdadfc9691480b99d82b232e15b) fix this?

**Comment by CharlieCorner** [comment]
It does, I forgot to say so on the Pull Request, I just added a quick comment there just for documenting purposes.

**Comment by jiaweihli** [comment]
Perfect 👍
