### ISSUE TITLE
Provide examples for 1.0 codebase

### ISSUE THREAD

**Issue by johnfigs** [jiaweihli/manga_downloader#91]
Hello, 

I am having issues figuring out how to start a download of One Piece from MangaStream. Could you provide some examples for the newer codebase? 

Thanks.

**Comment by Evolution0** [comment]
1.0.0: Last commit 2014.

Safe bet to say it is dead, even Mangopi isn't being worked on anymore. The master branch is actually updated more.

Also Mangopi doesn't have a Mangastream parser, so its not a valid source.

**Comment by Jfigs101** [comment]
Thanks Evo, do you know of any alternatives to this?

**Comment by johnfigs** [comment]
@Evolution0 Do you know of an alternative to this? Thanks.

**Comment by Evolution0** [comment]
Might be able to get what you want with the [Batoto Downloader](http://redsquirrel87.com/Batoto.php) in the mean time assuming you are trying to download a manga they have.

**Comment by jklmli** [comment]
Yes, 1.0.0 is on hold.  
[Mangopi](https://github.com/jiaweihli/mangopi) (a library to build clients with) is roughly usable, although the regexes are likely out of date.
